### ISSUE TITLE
Needs a donejs/devDependency on itsself

### ISSUE THREAD

**Issue by phillipskevin** [donejs/cli#70]
The dependency on `donejs-cli` was removed here: https://github.com/donejs/cli/commit/40c930895125c505dca25ef5ada44bbfc17dc588. This is needed so that you can run `donejs add ...` in a generated project after removing node_modules and re-installing. Without it, you get this error:

```
$ donejs add supermodel restaurant

Error: Could not find local DoneJS binary (/Users/kevin/dev/place-my-order-alpha/node_modules/.bin/donejs)
Allowed types for a new project are: app, plugin, generator
    at /Users/kevin/.nvm/versions/node/v6.9.4/lib/node_modules/donejs/lib/cli/run-binary.js:21:25
    at _fulfilled (/Users/kevin/.nvm/versions/node/v6.9.4/lib/node_modules/donejs/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/Users/kevin/.nvm/versions/node/v6.9.4/lib/node_modules/donejs/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/Users/kevin/.nvm/versions/node/v6.9.4/lib/node_modules/donejs/node_modules/q/q.js:796:13)
    at /Users/kevin/.nvm/versions/node/v6.9.4/lib/node_modules/donejs/node_modules/q/q.js:857:14
    at runSingle (/Users/kevin/.nvm/versions/node/v6.9.4/lib/node_modules/donejs/node_modules/q/q.js:137:13)
    at flush (/Users/kevin/.nvm/versions/node/v6.9.4/lib/node_modules/donejs/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:606:11)

```

**Comment by phillipskevin** [comment]
This is fixed in https://github.com/donejs/cli/commit/d4e9a601c35c4b80e77734d56deefdc4548ee1c0.

**Comment by phillipskevin** [comment]
This is also why `donejs develop` and other commands failed silently, which I didn't realize was happening until after this was fixed.
